blank_issues_enabled: true
contact_links:
  - name: Question or Discussion
    url: https://github.com/Korrojo/python-projects/discussions
    about: Ask questions or start discussions about the project
  - name: Security Vulnerability
    url: https://github.com/Korrojo/python-projects/security/advisories/new
    about: Report a security vulnerability (private disclosure)
